base: /
dependencies:
  - typo3/fluid-styled-content
  - maidem/site-package
languages:
  -
    title: German
    enabled: true
    locale: de_DE.utf8
    hreflang: ''
    base: /de/
    websiteTitle: ''
    navigationTitle: ''
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    locale: en_US.utf8
    hreflang: ''
    base: /en/
    websiteTitle: ''
    navigationTitle: ''
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
websiteTitle: ''
