base: /
dependencies:
  - typo3/fluid-styled-content
  - maidemde/taekwondo-mueller-sitepackage
languages:
  -
    title: German
    enabled: true
    locale: de_DE.utf8
    hreflang: ''
    base: /de/
    websiteTitle: ''
    navigationTitle: ''
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: ''
    base: /en/
    websiteTitle: ''
    navigationTitle: English
    fallbackType: strict
    fallbacks: '0'
    flag: en-us-gb
    languageId: 1
rootPageId: 3
websiteTitle: ''
